---

- name: 'Install {{ item.name }} script'
  template:
    src: '{{ item.template.src }}'
    dest: '{{ item.template.dest }}'
    owner: root
    group: root
    mode: 0755

- name: 'Install {{ item.name }} cron job'
  cron:
    user: 'postgres'
    name: '{{ item.name }}'
    hour: '{{ item.schedule.hour }}'
    minute: '{{ item.schedule.minute }}'
    weekday: '{{ item.schedule.weekday | default("*") }}'
    job: '{{ item.job }}'
